'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { AppContext } from './context/AppContext'
import { SessionProvider } from "next-auth/react";
import { ToasterWrap } from './components'

const inter = Montserrat({ subsets: ['latin'] })

 const metadata: Metadata = {
  title: 'Business Essentials',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`bg-black dark:bg-white ${inter.className}`}>
      <SessionProvider>
      <ToasterWrap/> 
      <AppContext>
        {children}
      </AppContext>
      </SessionProvider>
      </body>
    </html>
  )
}